[tool.black]
line-length = 88

[tool.pytest.ini_options]
addopts = "--tb=short -vv --xdoc --xdoctest-style=google"
log_cli_level = "INFO"
log_cli = true
log_cli_format = "%(asctime)s.%(msecs)03d %(levelname)-6s %(threadName)-10s '%(message)-s' %(name)10s.%(funcName)-22s"
junit_logging = "all"

[tool.mypy]
warn_return_any = false
ignore_missing_imports = true

[tool.ruff]
line-length = 88
target-version = "py39"
show-fixes = true
exclude = ["_pants/*.py"]
extend-ignore = ["E501", "UP006", "UP007", "UP035"]
extend-select = ["Q", "RUF100", "C90", "UP", "I", "T"]

[tool.ruff.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.isort]
known-first-party = ["tests"]

[tool.coverage.run]
omit = ["*/tests/**", "*/test/**"]